name = "lustre_limiter"
version = "1.0.0"

description = "Bringing debounce and throttle utilities to Lustre for the erlang target."
licences = ["MIT"]
repository = { type = "github", user = "7verdy", repo = "lustre-limiter" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
lustre = ">= 4.3.1 and < 5.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_javascript = ">= 0.11.0 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
